<?php include "../include/session.php";?>

<?php
if (isset($_GET['state_id'])) {
    # code...
    $state_id = @$_GET['state_id'];
    $state_id = intval($state_id);
    
} else {
    # code...
    $state_id = null;
}

$states = [
    [
        'id' => 1, 'option' => '', 'name' => 'Abia State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Aba North'],
            ['id' => 2, 'option' => '', 'name' => 'Aba South'],
            ['id' => 3, 'option' => '', 'name' => 'Arochukwu'],
            ['id' => 4, 'option' => '', 'name' => 'Bende'],
            ['id' => 5, 'option' => '', 'name' => 'Ikwuano'],
            ['id' => 6, 'option' => '', 'name' => 'Isiala-Ngwa North'],
            ['id' => 7, 'option' => '', 'name' => 'Isiala-Ngwa South'],
            ['id' => 8, 'option' => '', 'name' => 'Isuikwato'],
            ['id' => 9, 'option' => '', 'name' => 'Obi Nwa'],
            ['id' => 10, 'option' => '', 'name' => 'Ohafia'],
            ['id' => 11, 'option' => '', 'name' => 'Osisioma'],
            ['id' => 12, 'option' => '', 'name' => 'Ngwa'],
            ['id' => 13, 'option' => '', 'name' => 'Ugwunagbo'],
            ['id' => 14, 'option' => '', 'name' => 'Ukwa East'],
            ['id' => 15, 'option' => '', 'name' => 'Ukwa West'],
            ['id' => 16, 'option' => '', 'name' => 'Umuahia North'],
            ['id' => 17, 'option' => '', 'name' => 'Umuahia South'],
            ['id' => 18, 'option' => '', 'name' => 'Umu-Neochi'],
        ],
    ],
    [
        'id' => 2, 'option' => '', 'name' => 'Adamawa State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Demsa'],
            ['id' => 2, 'option' => '', 'name' => 'Fufore'],
            ['id' => 3, 'option' => '', 'name' => 'Ganaye'],
            ['id' => 4, 'option' => '', 'name' => 'Gireri'],
            ['id' => 5, 'option' => '', 'name' => 'Gombi'],
            ['id' => 6, 'option' => '', 'name' => 'Guyuk'],
            ['id' => 7, 'option' => '', 'name' => 'Hong'],
            ['id' => 8, 'option' => '', 'name' => 'Jada'],
            ['id' => 9, 'option' => '', 'name' => 'Lamurde'],
            ['id' => 10, 'option' => '', 'name' => 'Madagali'],
            ['id' => 11, 'option' => '', 'name' => 'Maiha'],
            ['id' => 12, 'option' => '', 'name' => 'Mayo-Belwa'],
            ['id' => 13, 'option' => '', 'name' => 'Michika'],
            ['id' => 14, 'option' => '', 'name' => 'Mubi North'],
            ['id' => 15, 'option' => '', 'name' => 'Mubi South'],
            ['id' => 16, 'option' => '', 'name' => 'Numan'],
            ['id' => 17, 'option' => '', 'name' => 'Shelleng'],
            ['id' => 18, 'option' => '', 'name' => 'Song'],
            ['id' => 19, 'option' => '', 'name' => 'Toungo'],
            ['id' => 20, 'option' => '', 'name' => 'Yola North'],
            ['id' => 21, 'option' => '', 'name' => 'Yola South'],
        ],
    ],
    [
        'id' => 3, 'option' => '', 'name' => 'Akwa Ibom State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Abak'],
            ['id' => 2, 'option' => '', 'name' => 'Eastern Obolo'],
            ['id' => 3, 'option' => '', 'name' => 'Eket'],
            ['id' => 4, 'option' => '', 'name' => 'Esit Eket'],
            ['id' => 5, 'option' => '', 'name' => 'Essien Udim'],
            ['id' => 6, 'option' => '', 'name' => 'Etim Ekpo'],
            ['id' => 7, 'option' => '', 'name' => 'Etinan'],
            ['id' => 8, 'option' => '', 'name' => 'Ibeno'],
            ['id' => 9, 'option' => '', 'name' => 'Ibesikpo Asutan'],
            ['id' => 10, 'option' => '', 'name' => 'Ibiono Ibom'],
            ['id' => 11, 'option' => '', 'name' => 'Ika'],
            ['id' => 12, 'option' => '', 'name' => 'Ikono'],
            ['id' => 13, 'option' => '', 'name' => 'Ikot Abasi'],
            ['id' => 14, 'option' => '', 'name' => 'Ikot Ekpene'],
            ['id' => 15, 'option' => '', 'name' => 'Ini'],
            ['id' => 16, 'option' => '', 'name' => 'Itu'],
            ['id' => 17, 'option' => '', 'name' => 'Mbo'],
            ['id' => 18, 'option' => '', 'name' => 'Mkpat Enin'],
            ['id' => 19, 'option' => '', 'name' => 'Nsit Atai'],
            ['id' => 20, 'option' => '', 'name' => 'Nsit Ibom'],
            ['id' => 21, 'option' => '', 'name' => 'Nsit Ubium'],
            ['id' => 22, 'option' => '', 'name' => 'Obot Akara'],
            ['id' => 23, 'option' => '', 'name' => 'Okobo'],
            ['id' => 24, 'option' => '', 'name' => 'Onna'],
            ['id' => 25, 'option' => '', 'name' => 'Oron'],
            ['id' => 26, 'option' => '', 'name' => 'Oruk Anam'],
            ['id' => 27, 'option' => '', 'name' => 'Udung Uko'],
            ['id' => 28, 'option' => '', 'name' => 'Ukanafun'],
            ['id' => 29, 'option' => '', 'name' => 'Uruan'],
            ['id' => 30, 'option' => '', 'name' => 'Urue-Offong/Oruko'],
            ['id' => 31, 'option' => '', 'name' => 'Uyo'],
        ],
    ],
    [
        'id' => 4, 'option' => '', 'name' => 'Anambara State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Aguata'],
            ['id' => 2, 'option' => '', 'name' => 'Anambra East'],
            ['id' => 3, 'option' => '', 'name' => 'Anambra West'],
            ['id' => 4, 'option' => '', 'name' => 'Anaocha'],
            ['id' => 5, 'option' => '', 'name' => 'Awka North'],
            ['id' => 6, 'option' => '', 'name' => 'Awka South'],
            ['id' => 7, 'option' => '', 'name' => 'Ayamelum'],
            ['id' => 8, 'option' => '', 'name' => 'Dunukofia'],
            ['id' => 9, 'option' => '', 'name' => 'Ekwusigo'],
            ['id' => 10, 'option' => '', 'name' => 'Idemili North'],
            ['id' => 11, 'option' => '', 'name' => 'Idemili south'],
            ['id' => 12, 'option' => '', 'name' => 'Ihiala'],
            ['id' => 13, 'option' => '', 'name' => 'Njikoka'],
            ['id' => 14, 'option' => '', 'name' => 'Nnewi North'],
            ['id' => 15, 'option' => '', 'name' => 'Nnewi South'],
            ['id' => 16, 'option' => '', 'name' => 'Ogbaru'],
            ['id' => 17, 'option' => '', 'name' => 'Onitsha North'],
            ['id' => 18, 'option' => '', 'name' => 'Onitsha South'],
            ['id' => 19, 'option' => '', 'name' => 'Orumba North'],
            ['id' => 20, 'option' => '', 'name' => 'Orumba South'],
            ['id' => 21, 'option' => '', 'name' => 'Oyi'],
        ],
    ],
    [
        'id' => 5, 'option' => '', 'name' => 'Bauchi State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Alkaleri'],
            ['id' => 2, 'option' => '', 'name' => 'Bauchi'],
            ['id' => 3, 'option' => '', 'name' => 'Bogoro'],
            ['id' => 4, 'option' => '', 'name' => 'Damban'],
            ['id' => 5, 'option' => '', 'name' => 'Darazo'],
            ['id' => 6, 'option' => '', 'name' => 'Dass'],
            ['id' => 7, 'option' => '', 'name' => 'Ganjuwa'],
            ['id' => 8, 'option' => '', 'name' => 'Giade'],
            ['id' => 9, 'option' => '', 'name' => 'Itas/Gadau'],
            ['id' => 10, 'option' => '', 'name' => 'Jama\'are'],
            ['id' => 11, 'option' => '', 'name' => 'Katagum'],
            ['id' => 12, 'option' => '', 'name' => 'Kirfi'],
            ['id' => 13, 'option' => '', 'name' => 'Misau'],
            ['id' => 14, 'option' => '', 'name' => 'Ningi'],
            ['id' => 15, 'option' => '', 'name' => 'Shira'],
            ['id' => 16, 'option' => '', 'name' => 'Tafawa-Balewa'],
            ['id' => 17, 'option' => '', 'name' => 'Toro'],
            ['id' => 18, 'option' => '', 'name' => 'Warji'],
            ['id' => 19, 'option' => '', 'name' => 'Zaki'],
            ['id' => 20, 'option' => '', 'name' => ''],
        ],
    ],
    [
        'id' => 6, 'option' => '', 'name' => 'Bayelsa State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Brass'],
            ['id' => 2, 'option' => '', 'name' => 'Ekeremor'],
            ['id' => 3, 'option' => '', 'name' => 'Kolokuma/Opokuma'],
            ['id' => 4, 'option' => '', 'name' => 'Nembe'],
            ['id' => 5, 'option' => '', 'name' => 'Ogbia'],
            ['id' => 6, 'option' => '', 'name' => 'Sagbama'],
            ['id' => 7, 'option' => '', 'name' => 'Southern Jaw'],
            ['id' => 8, 'option' => '', 'name' => 'Yenegoa'],
        ],
    ],
    [
        'id' => 7, 'option' => '', 'name' => 'Benue State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Ado'],
            ['id' => 2, 'option' => '', 'name' => 'Agatu'],
            ['id' => 3, 'option' => '', 'name' => 'Apa'],
            ['id' => 4, 'option' => '', 'name' => 'Buruku'],
            ['id' => 5, 'option' => '', 'name' => 'Gboko'],
            ['id' => 6, 'option' => '', 'name' => 'Guma'],
            ['id' => 7, 'option' => '', 'name' => 'Gwer East'],
            ['id' => 8, 'option' => '', 'name' => 'Gwer West'],
            ['id' => 9, 'option' => '', 'name' => 'Katsina-Ala'],
            ['id' => 10, 'option' => '', 'name' => 'Konshisha'],
            ['id' => 11, 'option' => '', 'name' => 'Kwande'],
            ['id' => 12, 'option' => '', 'name' => 'Logo'],
            ['id' => 13, 'option' => '', 'name' => 'Makurdi'],
            ['id' => 14, 'option' => '', 'name' => 'Obi'],
            ['id' => 15, 'option' => '', 'name' => 'Ogbadibo'],
            ['id' => 16, 'option' => '', 'name' => 'Oju'],
            ['id' => 17, 'option' => '', 'name' => 'Okpokwu'],
            ['id' => 18, 'option' => '', 'name' => 'Ohimini'],
            ['id' => 19, 'option' => '', 'name' => 'Oturkpo'],
            ['id' => 20, 'option' => '', 'name' => 'Tarka'],
            ['id' => 21, 'option' => '', 'name' => 'Ukum'],
            ['id' => 22, 'option' => '', 'name' => 'Ushongo'],
            ['id' => 23, 'option' => '', 'name' => 'Vandeikya'],
        ],
    ],
    [
        'id' => 8, 'option' => '', 'name' => 'Borno State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Abadam'],
            ['id' => 2, 'option' => '', 'name' => 'Askira/Uba'],
            ['id' => 3, 'option' => '', 'name' => 'Bama'],
            ['id' => 4, 'option' => '', 'name' => 'Bayo'],
            ['id' => 5, 'option' => '', 'name' => 'Biu'],
            ['id' => 6, 'option' => '', 'name' => 'Chibok'],
            ['id' => 7, 'option' => '', 'name' => 'Damboa'],
            ['id' => 8, 'option' => '', 'name' => 'Dikwa'],
            ['id' => 9, 'option' => '', 'name' => 'Gubio'],
            ['id' => 10, 'option' => '', 'name' => 'Guzamala'],
            ['id' => 11, 'option' => '', 'name' => 'Gwoza'],
            ['id' => 12, 'option' => '', 'name' => 'Hawul'],
            ['id' => 13, 'option' => '', 'name' => 'Jere'],
            ['id' => 14, 'option' => '', 'name' => 'Kaga'],
            ['id' => 15, 'option' => '', 'name' => 'Kala/Balge'],
            ['id' => 16, 'option' => '', 'name' => 'Konduga'],
            ['id' => 17, 'option' => '', 'name' => 'Kukawa'],
            ['id' => 18, 'option' => '', 'name' => 'Kwaya Kusar'],
            ['id' => 19, 'option' => '', 'name' => 'Mafa'],
            ['id' => 20, 'option' => '', 'name' => 'Magumeri'],
            ['id' => 21, 'option' => '', 'name' => 'Maiduguri'],
            ['id' => 22, 'option' => '', 'name' => 'Marte'],
            ['id' => 23, 'option' => '', 'name' => 'Mobbar'],
            ['id' => 24, 'option' => '', 'name' => 'Monguno'],
            ['id' => 25, 'option' => '', 'name' => 'Ngala'],
            ['id' => 26, 'option' => '', 'name' => 'Nganzai'],
            ['id' => 27, 'option' => '', 'name' => 'Shani'],
        ],
    ],
    [
        'id' => 9, 'option' => '', 'name' => 'Cross-Rivers State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Akpabuyo'],
            ['id' => 2, 'option' => '', 'name' => 'Odukpani'],
            ['id' => 3, 'option' => '', 'name' => 'Akamkpa'],
            ['id' => 4, 'option' => '', 'name' => 'Biase'],
            ['id' => 5, 'option' => '', 'name' => 'Abi'],
            ['id' => 6, 'option' => '', 'name' => 'Ikom'],
            ['id' => 7, 'option' => '', 'name' => 'Yarkur'],
            ['id' => 8, 'option' => '', 'name' => 'Odubra'],
            ['id' => 9, 'option' => '', 'name' => 'Boki'],
            ['id' => 10, 'option' => '', 'name' => 'Ogoja'],
            ['id' => 11, 'option' => '', 'name' => 'Yala'],
            ['id' => 12, 'option' => '', 'name' => 'Obanliku'],
            ['id' => 13, 'option' => '', 'name' => 'Obudu'],
            ['id' => 14, 'option' => '', 'name' => 'Calabar South'],
            ['id' => 15, 'option' => '', 'name' => 'Etung'],
            ['id' => 16, 'option' => '', 'name' => 'Bekwara'],
            ['id' => 17, 'option' => '', 'name' => 'Bakassi'],
            ['id' => 18, 'option' => '', 'name' => 'Calabar Municipality'],
        ],
    ],
    [
        'id' => 10, 'option' => '', 'name' => 'Delta State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Oshimili'],
            ['id' => 2, 'option' => '', 'name' => 'Aniocha'],
            ['id' => 3, 'option' => '', 'name' => 'Aniocha South'],
            ['id' => 4, 'option' => '', 'name' => 'Ika South'],
            ['id' => 5, 'option' => '', 'name' => 'Ika North-East'],
            ['id' => 6, 'option' => '', 'name' => 'Ndokwa West'],
            ['id' => 7, 'option' => '', 'name' => 'Ndokwa East'],
            ['id' => 8, 'option' => '', 'name' => 'Isoko south'],
            ['id' => 9, 'option' => '', 'name' => 'Isoko North'],
            ['id' => 10, 'option' => '', 'name' => 'Bomadi'],
            ['id' => 11, 'option' => '', 'name' => 'Burutu'],
            ['id' => 12, 'option' => '', 'name' => 'Ughelli South'],
            ['id' => 13, 'option' => '', 'name' => 'Ughelli North'],
            ['id' => 14, 'option' => '', 'name' => 'Ethiope West'],
            ['id' => 15, 'option' => '', 'name' => 'Ethiope East'],
            ['id' => 16, 'option' => '', 'name' => 'Sapele'],
            ['id' => 17, 'option' => '', 'name' => 'Okpe'],
            ['id' => 18, 'option' => '', 'name' => 'Warri North'],
            ['id' => 19, 'option' => '', 'name' => 'Warri South'],
            ['id' => 20, 'option' => '', 'name' => 'Uvwie'],
            ['id' => 21, 'option' => '', 'name' => 'Udu'],
            ['id' => 22, 'option' => '', 'name' => 'Warri Central'],
            ['id' => 23, 'option' => '', 'name' => 'Ukwani'],
            ['id' => 24, 'option' => '', 'name' => 'Oshimili North'],
            ['id' => 25, 'option' => '', 'name' => 'Patani'],
        ],
    ],
    [
        'id' => 11, 'option' => '', 'name' => 'Ebonyi State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Afikpo South'],
            ['id' => 2, 'option' => '', 'name' => 'Afikpo North'],
            ['id' => 3, 'option' => '', 'name' => 'Onicha'],
            ['id' => 4, 'option' => '', 'name' => 'Ohaozara'],
            ['id' => 5, 'option' => '', 'name' => 'Abakaliki'],
            ['id' => 6, 'option' => '', 'name' => 'Ishielu'],
            ['id' => 7, 'option' => '', 'name' => 'lkwo'],
            ['id' => 8, 'option' => '', 'name' => 'Ezza'],
            ['id' => 9, 'option' => '', 'name' => 'Ezza South'],
            ['id' => 10, 'option' => '', 'name' => 'Ohaukwu'],
            ['id' => 11, 'option' => '', 'name' => 'Ebonyi'],
            ['id' => 12, 'option' => '', 'name' => 'Ivo'],
        ],
    ],
    [
        'id' => 12, 'option' => '', 'name' => 'Edo State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Esan North-East'],
            ['id' => 2, 'option' => '', 'name' => 'Esan Central'],
            ['id' => 3, 'option' => '', 'name' => 'Esan West'],
            ['id' => 4, 'option' => '', 'name' => 'Egor'],
            ['id' => 5, 'option' => '', 'name' => 'Ukpoba'],
            ['id' => 6, 'option' => '', 'name' => 'Central'],
            ['id' => 7, 'option' => '', 'name' => 'Etsako Central'],
            ['id' => 8, 'option' => '', 'name' => 'Igueben'],
            ['id' => 9, 'option' => '', 'name' => 'Oredo'],
            ['id' => 10, 'option' => '', 'name' => 'Ovia SouthWest'],
            ['id' => 11, 'option' => '', 'name' => 'Ovia South-East'],
            ['id' => 12, 'option' => '', 'name' => 'Orhionwon'],
            ['id' => 13, 'option' => '', 'name' => 'Uhunmwonde'],
            ['id' => 14, 'option' => '', 'name' => 'Etsako East'],
            ['id' => 15, 'option' => '', 'name' => 'Esan South-East'],
        ],
    ],
    [
        'id' => 13, 'option' => '', 'name' => 'Ekiti State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Ado'],
            ['id' => 2, 'option' => '', 'name' => 'Ekiti-East'],
            ['id' => 3, 'option' => '', 'name' => 'Ekiti-West'],
            ['id' => 4, 'option' => '', 'name' => 'Emure/Ise/Orun'],
            ['id' => 5, 'option' => '', 'name' => 'Ekiti South-West'],
            ['id' => 6, 'option' => '', 'name' => 'Ikare'],
            ['id' => 7, 'option' => '', 'name' => 'Irepodun'],
            ['id' => 8, 'option' => '', 'name' => 'Ijero,'],
            ['id' => 9, 'option' => '', 'name' => 'Ido/Osi'],
            ['id' => 10, 'option' => '', 'name' => 'Oye'],
            ['id' => 11, 'option' => '', 'name' => 'Ikole'],
            ['id' => 12, 'option' => '', 'name' => 'Moba'],
            ['id' => 13, 'option' => '', 'name' => 'Gbonyin'],
            ['id' => 14, 'option' => '', 'name' => 'Efon'],
            ['id' => 15, 'option' => '', 'name' => 'Ise/Orun'],
            ['id' => 16, 'option' => '', 'name' => 'Ilejemeje'],
        ],
    ],
    [
        'id' => 14, 'option' => '', 'name' => 'Enugu State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Enugu South'],
            ['id' => 2, 'option' => '', 'name' => 'Igbo-Eze South'],
            ['id' => 3, 'option' => '', 'name' => 'Enugu North'],
            ['id' => 4, 'option' => '', 'name' => 'Nkanu'],
            ['id' => 5, 'option' => '', 'name' => 'Udi Agwu'],
            ['id' => 6, 'option' => '', 'name' => 'Oji-River'],
            ['id' => 7, 'option' => '', 'name' => 'Ezeagu'],
            ['id' => 8, 'option' => '', 'name' => 'IgboEze North'],
            ['id' => 9, 'option' => '', 'name' => 'Isi-Uzo'],
            ['id' => 10, 'option' => '', 'name' => 'Nsukka'],
            ['id' => 11, 'option' => '', 'name' => 'Igbo-Ekiti'],
            ['id' => 12, 'option' => '', 'name' => 'Uzo-Uwani'],
            ['id' => 13, 'option' => '', 'name' => 'Enugu Eas'],
            ['id' => 14, 'option' => '', 'name' => 'Aninri'],
            ['id' => 15, 'option' => '', 'name' => 'Nkanu East'],
            ['id' => 16, 'option' => '', 'name' => 'Udenu'],
        ],
    ],
    [
        'id' => 15, 'option' => '', 'name' => 'Gombe State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Akko'],
            ['id' => 2, 'option' => '', 'name' => 'Balanga'],
            ['id' => 3, 'option' => '', 'name' => 'Billiri'],
            ['id' => 4, 'option' => '', 'name' => 'Dukku'],
            ['id' => 5, 'option' => '', 'name' => 'Kaltungo'],
            ['id' => 6, 'option' => '', 'name' => 'Kwami'],
            ['id' => 7, 'option' => '', 'name' => 'Shomgom'],
            ['id' => 8, 'option' => '', 'name' => 'Funakaye'],
            ['id' => 9, 'option' => '', 'name' => 'Gombe'],
            ['id' => 10, 'option' => '', 'name' => 'Nafada/Bajoga'],
            ['id' => 11, 'option' => '', 'name' => 'Yamaltu/Delta'],
        ],
    ],
    [
        'id' => 16, 'option' => '', 'name' => 'Imo State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Aboh-Mbaise'],
            ['id' => 2, 'option' => '', 'name' => 'Ahiazu-Mbaise'],
            ['id' => 3, 'option' => '', 'name' => 'Ehime-Mbano'],
            ['id' => 4, 'option' => '', 'name' => 'Ezinihitte'],
            ['id' => 5, 'option' => '', 'name' => 'Ideato North'],
            ['id' => 6, 'option' => '', 'name' => 'Ideato South'],
            ['id' => 7, 'option' => '', 'name' => 'Ihitte/Uboma'],
            ['id' => 8, 'option' => '', 'name' => 'Ikeduru'],
            ['id' => 9, 'option' => '', 'name' => 'Isiala Mbano'],
            ['id' => 10, 'option' => '', 'name' => 'Isu'],
            ['id' => 11, 'option' => '', 'name' => 'Mbaitoli'],
            ['id' => 12, 'option' => '', 'name' => 'Mbaitoli'],
            ['id' => 13, 'option' => '', 'name' => 'Ngor-Okpala'],
            ['id' => 14, 'option' => '', 'name' => 'Njaba'],
            ['id' => 15, 'option' => '', 'name' => 'Nwangele'],
            ['id' => 16, 'option' => '', 'name' => 'Nkwerre'],
            ['id' => 17, 'option' => '', 'name' => 'Obowo'],
            ['id' => 18, 'option' => '', 'name' => 'Oguta'],
            ['id' => 19, 'option' => '', 'name' => 'Ohaji/Egbema'],
            ['id' => 20, 'option' => '', 'name' => 'Okigwe'],
            ['id' => 21, 'option' => '', 'name' => 'Orlu'],
            ['id' => 22, 'option' => '', 'name' => 'Orsu'],
            ['id' => 23, 'option' => '', 'name' => 'Oru East'],
            ['id' => 24, 'option' => '', 'name' => 'Oru West'],
            ['id' => 25, 'option' => '', 'name' => 'Owerri-Municipal'],
            ['id' => 26, 'option' => '', 'name' => 'Owerri North'],
            ['id' => 27, 'option' => '', 'name' => 'Owerri West'],
        ],
    ],
    [
        'id' => 17, 'option' => '', 'name' => 'Jigawa State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Auyo'],
            ['id' => 2, 'option' => '', 'name' => 'Babura'],
            ['id' => 3, 'option' => '', 'name' => 'Birni Kudu'],
            ['id' => 4, 'option' => '', 'name' => 'Biriniwa'],
            ['id' => 5, 'option' => '', 'name' => 'Buji'],
            ['id' => 6, 'option' => '', 'name' => 'Dutse'],
            ['id' => 7, 'option' => '', 'name' => 'Gagarawa'],
            ['id' => 8, 'option' => '', 'name' => 'Garki'],
            ['id' => 9, 'option' => '', 'name' => 'Gumel'],
            ['id' => 10, 'option' => '', 'name' => 'Guri'],
            ['id' => 11, 'option' => '', 'name' => 'Gwaram'],
            ['id' => 12, 'option' => '', 'name' => 'Gwiwa'],
            ['id' => 13, 'option' => '', 'name' => 'Hadejia'],
            ['id' => 14, 'option' => '', 'name' => 'Jahun'],
            ['id' => 15, 'option' => '', 'name' => 'Kafin Hausa'],
            ['id' => 16, 'option' => '', 'name' => 'Kaugama Kazaure'],
            ['id' => 17, 'option' => '', 'name' => 'Kiri Kasamma'],
            ['id' => 18, 'option' => '', 'name' => 'Kiyawa'],
            ['id' => 19, 'option' => '', 'name' => 'Maigatari'],
            ['id' => 20, 'option' => '', 'name' => 'Malam Madori'],
            ['id' => 21, 'option' => '', 'name' => 'Miga'],
            ['id' => 22, 'option' => '', 'name' => 'Ringim'],
            ['id' => 23, 'option' => '', 'name' => 'Roni'],
            ['id' => 24, 'option' => '', 'name' => 'Sule-Tankarkar'],
            ['id' => 25, 'option' => '', 'name' => 'Taura'],
            ['id' => 26, 'option' => '', 'name' => 'Yankwashi'],
        ],
    ],
    [
        'id' => 18, 'option' => '', 'name' => 'Kaduna State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Birni-Gwari'],
            ['id' => 2, 'option' => '', 'name' => 'Chikun'],
            ['id' => 3, 'option' => '', 'name' => 'Giwa'],
            ['id' => 4, 'option' => '', 'name' => 'Igabi'],
            ['id' => 5, 'option' => '', 'name' => 'Ikara'],
            ['id' => 6, 'option' => '', 'name' => 'jaba'],
            ['id' => 7, 'option' => '', 'name' => 'Jema\'a'],
            ['id' => 8, 'option' => '', 'name' => 'Kachia'],
            ['id' => 9, 'option' => '', 'name' => 'Kaduna North'],
            ['id' => 10, 'option' => '', 'name' => 'Kaduna South'],
            ['id' => 11, 'option' => '', 'name' => 'Kagarko'],
            ['id' => 12, 'option' => '', 'name' => 'Kajuru'],
            ['id' => 13, 'option' => '', 'name' => 'Kaura'],
            ['id' => 14, 'option' => '', 'name' => 'Kauru'],
            ['id' => 15, 'option' => '', 'name' => 'Kubau'],
            ['id' => 16, 'option' => '', 'name' => 'Kudan'],
            ['id' => 17, 'option' => '', 'name' => 'Lere'],
            ['id' => 18, 'option' => '', 'name' => 'Makarfi'],
            ['id' => 19, 'option' => '', 'name' => 'Sabon-Gari'],
            ['id' => 20, 'option' => '', 'name' => 'Sanga'],
            ['id' => 21, 'option' => '', 'name' => 'Soba'],
            ['id' => 22, 'option' => '', 'name' => 'Zango-Kataf'],
            ['id' => 23, 'option' => '', 'name' => 'Zaria'],
        ],
    ],
    [
        'id' => 19, 'option' => '', 'name' => 'Kano State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Ajingi'],
            ['id' => 2, 'option' => '', 'name' => 'Albasu'],
            ['id' => 3, 'option' => '', 'name' => 'Bagwai'],
            ['id' => 4, 'option' => '', 'name' => 'Bebeji'],
            ['id' => 5, 'option' => '', 'name' => 'Bichi'],
            ['id' => 6, 'option' => '', 'name' => 'Bunkure'],
            ['id' => 7, 'option' => '', 'name' => 'Dala'],
            ['id' => 8, 'option' => '', 'name' => 'Dambatta'],
            ['id' => 9, 'option' => '', 'name' => 'Dawakin Kudu'],
            ['id' => 10, 'option' => '', 'name' => 'Dawakin Tofa'],
            ['id' => 11, 'option' => '', 'name' => 'Doguwa'],
            ['id' => 12, 'option' => '', 'name' => 'Fagge'],
            ['id' => 13, 'option' => '', 'name' => 'Gabasawa'],
            ['id' => 14, 'option' => '', 'name' => 'Garko'],
            ['id' => 15, 'option' => '', 'name' => 'Garum'],
            ['id' => 16, 'option' => '', 'name' => 'Mallam'],
            ['id' => 17, 'option' => '', 'name' => 'Gaya'],
            ['id' => 18, 'option' => '', 'name' => 'Gezawa'],
            ['id' => 19, 'option' => '', 'name' => 'Gwale'],
            ['id' => 20, 'option' => '', 'name' => 'Gwarzo'],
            ['id' => 21, 'option' => '', 'name' => 'Kabo'],
            ['id' => 22, 'option' => '', 'name' => 'Kano Municipal'],
            ['id' => 23, 'option' => '', 'name' => 'Karaye'],
            ['id' => 24, 'option' => '', 'name' => 'Kibiya'],
            ['id' => 25, 'option' => '', 'name' => 'Kiru'],
            ['id' => 26, 'option' => '', 'name' => 'kumbotso'],
            ['id' => 27, 'option' => '', 'name' => 'Kunchi'],
            ['id' => 28, 'option' => '', 'name' => 'Kura'],
            ['id' => 29, 'option' => '', 'name' => 'Madobi'],
            ['id' => 30, 'option' => '', 'name' => 'Makoda'],
            ['id' => 31, 'option' => '', 'name' => 'Minjibir'],
            ['id' => 32, 'option' => '', 'name' => 'Nasarawa'],
            ['id' => 33, 'option' => '', 'name' => 'Rano'],
            ['id' => 34, 'option' => '', 'name' => 'Rimin Gado'],
            ['id' => 35, 'option' => '', 'name' => 'Rogo'],
            ['id' => 36, 'option' => '', 'name' => 'Shanono'],
            ['id' => 37, 'option' => '', 'name' => 'Sumaila'],
            ['id' => 38, 'option' => '', 'name' => 'Takali'],
            ['id' => 39, 'option' => '', 'name' => 'Tarauni'],
            ['id' => 40, 'option' => '', 'name' => 'Tofa'],
            ['id' => 41, 'option' => '', 'name' => 'Tsanyawa'],
            ['id' => 42, 'option' => '', 'name' => 'Tudun Wada'],
            ['id' => 43, 'option' => '', 'name' => 'Ungogo'],
            ['id' => 44, 'option' => '', 'name' => 'Warawa'],
            ['id' => 45, 'option' => '', 'name' => 'Wudil'],
        ],
    ],
    [
        'id' => 20, 'option' => '', 'name' => 'Katsina State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Bakori'],
            ['id' => 2, 'option' => '', 'name' => 'Batagarawa'],
            ['id' => 3, 'option' => '', 'name' => 'Batsari'],
            ['id' => 4, 'option' => '', 'name' => 'Baure'],
            ['id' => 5, 'option' => '', 'name' => 'Bindawa'],
            ['id' => 6, 'option' => '', 'name' => 'Charanchi'],
            ['id' => 7, 'option' => '', 'name' => 'Dandume'],
            ['id' => 8, 'option' => '', 'name' => 'Danja'],
            ['id' => 9, 'option' => '', 'name' => 'Dan Musa'],
            ['id' => 10, 'option' => '', 'name' => 'Daura'],
            ['id' => 11, 'option' => '', 'name' => 'Dutsi'],
            ['id' => 12, 'option' => '', 'name' => 'Dutsin-Ma'],
            ['id' => 13, 'option' => '', 'name' => 'Faskari'],
            ['id' => 14, 'option' => '', 'name' => 'Funtua'],
            ['id' => 15, 'option' => '', 'name' => 'Ingawa'],
            ['id' => 16, 'option' => '', 'name' => 'Jibia'],
            ['id' => 17, 'option' => '', 'name' => 'Kafur'],
            ['id' => 18, 'option' => '', 'name' => 'Kaita'],
            ['id' => 19, 'option' => '', 'name' => 'Kankara'],
            ['id' => 20, 'option' => '', 'name' => 'Kankia'],
            ['id' => 21, 'option' => '', 'name' => 'Katsina'],
            ['id' => 22, 'option' => '', 'name' => 'Kurfi'],
            ['id' => 23, 'option' => '', 'name' => 'Kusada'],
            ['id' => 24, 'option' => '', 'name' => 'Mai\'Adua'],
            ['id' => 25, 'option' => '', 'name' => 'Malumfashi'],
            ['id' => 26, 'option' => '', 'name' => 'Mani'],
            ['id' => 27, 'option' => '', 'name' => 'Mashi'],
            ['id' => 28, 'option' => '', 'name' => 'Matazuu'],
            ['id' => 29, 'option' => '', 'name' => 'Musawa'],
            ['id' => 30, 'option' => '', 'name' => 'Rimi'],
            ['id' => 31, 'option' => '', 'name' => 'Sabuwa'],
            ['id' => 32, 'option' => '', 'name' => 'Safana'],
            ['id' => 33, 'option' => '', 'name' => 'Sandamu'],
            ['id' => 34, 'option' => '', 'name' => 'Zango'],
        ],
    ],
    [
        'id' => 21, 'option' => '', 'name' => 'Kebbi State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Aleiro'],
            ['id' => 2, 'option' => '', 'name' => 'Arewa-Dandi'],
            ['id' => 3, 'option' => '', 'name' => 'Argungu'],
            ['id' => 4, 'option' => '', 'name' => 'Augie'],
            ['id' => 5, 'option' => '', 'name' => 'Bagudo'],
            ['id' => 6, 'option' => '', 'name' => 'Birnin Kebbi'],
            ['id' => 7, 'option' => '', 'name' => 'Bunza'],
            ['id' => 8, 'option' => '', 'name' => 'Dandi'],
            ['id' => 9, 'option' => '', 'name' => 'Fakai'],
            ['id' => 10, 'option' => '', 'name' => 'Gwandu'],
            ['id' => 11, 'option' => '', 'name' => 'Jega'],
            ['id' => 12, 'option' => '', 'name' => 'Kalgo'],
            ['id' => 13, 'option' => '', 'name' => 'Koko/Besse'],
            ['id' => 14, 'option' => '', 'name' => 'Maiyama'],
            ['id' => 15, 'option' => '', 'name' => 'Ngaski'],
            ['id' => 16, 'option' => '', 'name' => 'Sakaba'],
            ['id' => 17, 'option' => '', 'name' => 'Shanga'],
            ['id' => 18, 'option' => '', 'name' => 'Suru'],
            ['id' => 19, 'option' => '', 'name' => 'Wasagu/Danko'],
            ['id' => 20, 'option' => '', 'name' => 'Yauri'],
            ['id' => 21, 'option' => '', 'name' => 'Zuru'],
        ],
    ],
    [
        'id' => 22, 'option' => '', 'name' => 'Kogi State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Adavi'],
            ['id' => 2, 'option' => '', 'name' => 'Ajaokuta'],
            ['id' => 3, 'option' => '', 'name' => 'Ankpa'],
            ['id' => 4, 'option' => '', 'name' => 'Bassa'],
            ['id' => 5, 'option' => '', 'name' => 'Dekina'],
            ['id' => 6, 'option' => '', 'name' => 'Ibaji'],
            ['id' => 7, 'option' => '', 'name' => 'Idah'],
            ['id' => 8, 'option' => '', 'name' => 'Igalamela-Odolu'],
            ['id' => 9, 'option' => '', 'name' => 'Ijumu'],
            ['id' => 10, 'option' => '', 'name' => 'Kabba/Bunu'],
            ['id' => 11, 'option' => '', 'name' => 'Kogi'],
            ['id' => 12, 'option' => '', 'name' => 'Lokoja'],
            ['id' => 13, 'option' => '', 'name' => 'Mopa-Muro'],
            ['id' => 14, 'option' => '', 'name' => 'Ofu'],
            ['id' => 15, 'option' => '', 'name' => 'Ogori/Mangongo'],
            ['id' => 16, 'option' => '', 'name' => 'Okehi'],
            ['id' => 17, 'option' => '', 'name' => 'Okene'],
            ['id' => 18, 'option' => '', 'name' => 'Olamabolo'],
            ['id' => 19, 'option' => '', 'name' => 'Omala'],
            ['id' => 20, 'option' => '', 'name' => 'Yagba East'],
            ['id' => 21, 'option' => '', 'name' => 'Yagba West'],
        ],
    ],
    [
        'id' => 23, 'option' => '', 'name' => 'Kwara State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Asa'],
            ['id' => 2, 'option' => '', 'name' => 'Baruten'],
            ['id' => 3, 'option' => '', 'name' => 'Edu'],
            ['id' => 4, 'option' => '', 'name' => 'Ekiti'],
            ['id' => 5, 'option' => '', 'name' => 'Ifelodun'],
            ['id' => 6, 'option' => '', 'name' => 'Ilorin East'],
            ['id' => 7, 'option' => '', 'name' => 'Ilorin West'],
            ['id' => 8, 'option' => '', 'name' => 'Irepodun'],
            ['id' => 9, 'option' => '', 'name' => 'Isin'],
            ['id' => 10, 'option' => '', 'name' => 'Kaiama'],
            ['id' => 11, 'option' => '', 'name' => 'Moro'],
            ['id' => 12, 'option' => '', 'name' => 'Offa'],
            ['id' => 13, 'option' => '', 'name' => 'Oke-Ero'],
            ['id' => 14, 'option' => '', 'name' => 'Oyun'],
            ['id' => 15, 'option' => '', 'name' => 'Pategi'],
        ],
    ],
    [
        'id' => 24, 'option' => '', 'name' => 'Lagos State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Agege'],
            ['id' => 2, 'option' => '', 'name' => 'Ajeromi-Ifelodun'],
            ['id' => 3, 'option' => '', 'name' => 'Alimosho'],
            ['id' => 4, 'option' => '', 'name' => 'Amuwo-Odofin'],
            ['id' => 5, 'option' => '', 'name' => 'Apapa'],
            ['id' => 6, 'option' => '', 'name' => 'Badagry'],
            ['id' => 7, 'option' => '', 'name' => 'Epe'],
            ['id' => 8, 'option' => '', 'name' => 'Eti-Osa'],
            ['id' => 9, 'option' => '', 'name' => 'Ibeju/Lekki'],
            ['id' => 10, 'option' => '', 'name' => 'Ifako-Ijaye'],
            ['id' => 11, 'option' => '', 'name' => 'Ikeja'],
            ['id' => 12, 'option' => '', 'name' => 'Ikorodu'],
            ['id' => 13, 'option' => '', 'name' => 'Kosofe'],
            ['id' => 14, 'option' => '', 'name' => 'Lagos Island'],
            ['id' => 15, 'option' => '', 'name' => 'Lagos Mainland'],
            ['id' => 16, 'option' => '', 'name' => 'Mushin'],
            ['id' => 17, 'option' => '', 'name' => 'Ojo'],
            ['id' => 18, 'option' => '', 'name' => 'Oshodi-Isolo'],
            ['id' => 19, 'option' => '', 'name' => 'Shomolu'],
            ['id' => 20, 'option' => '', 'name' => 'Surulere'],
        ],
    ],
    [
        'id' => 25, 'option' => '', 'name' => 'Nassarawa State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Akwanga'],
            ['id' => 2, 'option' => '', 'name' => 'Awe'],
            ['id' => 3, 'option' => '', 'name' => 'Doma'],
            ['id' => 4, 'option' => '', 'name' => 'Karu'],
            ['id' => 5, 'option' => '', 'name' => 'Keana'],
            ['id' => 6, 'option' => '', 'name' => 'Keffi'],
            ['id' => 7, 'option' => '', 'name' => 'Kokona'],
            ['id' => 8, 'option' => '', 'name' => 'Lafia'],
            ['id' => 9, 'option' => '', 'name' => 'Nasarawa'],
            ['id' => 10, 'option' => '', 'name' => 'Nasarawa-Eggon'],
            ['id' => 11, 'option' => '', 'name' => 'Obi'],
            ['id' => 12, 'option' => '', 'name' => 'Toto'],
            ['id' => 13, 'option' => '', 'name' => 'Wamba'],
        ],
    ],
    [
        'id' => 26, 'option' => '', 'name' => 'Niger State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Agaie'],
            ['id' => 2, 'option' => '', 'name' => 'Agwara'],
            ['id' => 3, 'option' => '', 'name' => 'Bida'],
            ['id' => 4, 'option' => '', 'name' => 'Borgu'],
            ['id' => 5, 'option' => '', 'name' => 'Bosso'],
            ['id' => 6, 'option' => '', 'name' => 'Chanchaga'],
            ['id' => 7, 'option' => '', 'name' => 'Edati'],
            ['id' => 8, 'option' => '', 'name' => 'Gbako'],
            ['id' => 9, 'option' => '', 'name' => 'Gurara'],
            ['id' => 10, 'option' => '', 'name' => 'Katcha'],
            ['id' => 11, 'option' => '', 'name' => 'Kontagora'],
            ['id' => 12, 'option' => '', 'name' => 'Lapai'],
            ['id' => 13, 'option' => '', 'name' => 'Lavun'],
            ['id' => 14, 'option' => '', 'name' => 'Magama'],
            ['id' => 15, 'option' => '', 'name' => 'Mariga'],
            ['id' => 16, 'option' => '', 'name' => 'Mashegu'],
            ['id' => 17, 'option' => '', 'name' => 'Mokwa'],
            ['id' => 18, 'option' => '', 'name' => 'Muya'],
            ['id' => 19, 'option' => '', 'name' => 'Pailoro'],
            ['id' => 20, 'option' => '', 'name' => 'Rafi'],
            ['id' => 21, 'option' => '', 'name' => 'Rijau'],
            ['id' => 22, 'option' => '', 'name' => 'Shiroro'],
            ['id' => 23, 'option' => '', 'name' => 'Suleja'],
            ['id' => 24, 'option' => '', 'name' => 'Tafa'],
            ['id' => 25, 'option' => '', 'name' => 'Wushishi'],
        ],
    ],
    [
        'id' => 27, 'option' => '', 'name' => 'Ogun State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Abeokuta North'],
            ['id' => 2, 'option' => '', 'name' => 'Abeokuta South'],
            ['id' => 3, 'option' => '', 'name' => 'Ado-Odo/Ota'],
            ['id' => 4, 'option' => '', 'name' => 'Egbado North'],
            ['id' => 5, 'option' => '', 'name' => 'Egbado South'],
            ['id' => 6, 'option' => '', 'name' => 'Ewekoro'],
            ['id' => 7, 'option' => '', 'name' => 'Ifo'],
            ['id' => 8, 'option' => '', 'name' => 'Ijebu East'],
            ['id' => 9, 'option' => '', 'name' => 'Ijebu North'],
            ['id' => 10, 'option' => '', 'name' => 'Ijebu North East'],
            ['id' => 11, 'option' => '', 'name' => 'Ijebu Ode'],
            ['id' => 12, 'option' => '', 'name' => 'Ikenne'],
            ['id' => 13, 'option' => '', 'name' => 'Imeko-Afon'],
            ['id' => 14, 'option' => '', 'name' => 'Ipokia'],
            ['id' => 15, 'option' => '', 'name' => 'Obafemi-Owode'],
            ['id' => 16, 'option' => '', 'name' => 'Ogun Waterside'],
            ['id' => 17, 'option' => '', 'name' => 'Odeda'],
            ['id' => 18, 'option' => '', 'name' => 'Odogbolu'],
            ['id' => 19, 'option' => '', 'name' => 'Remo North'],
            ['id' => 20, 'option' => '', 'name' => 'Shagamu'],
        ],
    ],
    [
        'id' => 28, 'option' => '', 'name' => 'Ondo State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Akoko North East'],
            ['id' => 2, 'option' => '', 'name' => 'Akoko North West'],
            ['id' => 3, 'option' => '', 'name' => 'Akoko South Akure East'],
            ['id' => 4, 'option' => '', 'name' => 'Akoko South West'],
            ['id' => 5, 'option' => '', 'name' => 'Akure North'],
            ['id' => 6, 'option' => '', 'name' => 'Akure South'],
            ['id' => 7, 'option' => '', 'name' => 'Ese-Odo'],
            ['id' => 8, 'option' => '', 'name' => 'Idanre'],
            ['id' => 9, 'option' => '', 'name' => 'Ifedore'],
            ['id' => 10, 'option' => '', 'name' => 'Ilaje'],
            ['id' => 11, 'option' => '', 'name' => 'Ile-Oluji'],
            ['id' => 12, 'option' => '', 'name' => 'Okeigbo'],
            ['id' => 13, 'option' => '', 'name' => 'Irele'],
            ['id' => 14, 'option' => '', 'name' => 'Odigbo'],
            ['id' => 15, 'option' => '', 'name' => 'Okitipupa'],
            ['id' => 16, 'option' => '', 'name' => 'Ondo East'],
            ['id' => 17, 'option' => '', 'name' => 'Ondo West'],
            ['id' => 18, 'option' => '', 'name' => 'Ose'],
            ['id' => 19, 'option' => '', 'name' => 'Owo'],
        ],
    ],
    [
        'id' => 29, 'option' => '', 'name' => 'Osun State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Aiyedade'],
            ['id' => 2, 'option' => '', 'name' => 'Aiyedire'],
            ['id' => 3, 'option' => '', 'name' => 'Atakumosa East'],
            ['id' => 4, 'option' => '', 'name' => 'Atakumosa West'],
            ['id' => 5, 'option' => '', 'name' => 'Boluwaduro'],
            ['id' => 6, 'option' => '', 'name' => 'Boripe'],
            ['id' => 7, 'option' => '', 'name' => 'Ede North'],
            ['id' => 8, 'option' => '', 'name' => 'Ede South'],
            ['id' => 9, 'option' => '', 'name' => 'Egbedore'],
            ['id' => 10, 'option' => '', 'name' => 'Ejigbo'],
            ['id' => 11, 'option' => '', 'name' => 'Ife Central'],
            ['id' => 12, 'option' => '', 'name' => 'Ife East'],
            ['id' => 13, 'option' => '', 'name' => 'Ife North'],
            ['id' => 14, 'option' => '', 'name' => 'Ife South'],
            ['id' => 15, 'option' => '', 'name' => 'Ifedayo'],
            ['id' => 16, 'option' => '', 'name' => 'Ifelodun'],
            ['id' => 17, 'option' => '', 'name' => 'Ila'],
            ['id' => 18, 'option' => '', 'name' => 'Ilesha East'],
            ['id' => 19, 'option' => '', 'name' => 'Ilesha West'],
            ['id' => 20, 'option' => '', 'name' => 'Irepodun'],
            ['id' => 21, 'option' => '', 'name' => 'Irewole'],
            ['id' => 22, 'option' => '', 'name' => 'Isokan'],
            ['id' => 23, 'option' => '', 'name' => 'Iwo'],
            ['id' => 24, 'option' => '', 'name' => 'Obokun'],
            ['id' => 25, 'option' => '', 'name' => 'Odo-Otin'],
            ['id' => 26, 'option' => '', 'name' => 'Ola-Oluwa'],
            ['id' => 27, 'option' => '', 'name' => 'Olorunda'],
            ['id' => 28, 'option' => '', 'name' => 'Oriade'],
            ['id' => 29, 'option' => '', 'name' => 'Orolu'],
            ['id' => 30, 'option' => '', 'name' => 'Osogbo'],
        ],
    ],
    [
        'id' => 30, 'option' => '', 'name' => 'Oyo State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Afijio'],
            ['id' => 2, 'option' => '', 'name' => 'Akinyele'],
            ['id' => 3, 'option' => '', 'name' => 'Atiba'],
            ['id' => 4, 'option' => '', 'name' => 'Atigbo'],
            ['id' => 5, 'option' => '', 'name' => 'Egbeda'],
            ['id' => 6, 'option' => '', 'name' => 'IbadanCentral'],
            ['id' => 7, 'option' => '', 'name' => 'Ibadan North'],
            ['id' => 8, 'option' => '', 'name' => 'Ibadan North West'],
            ['id' => 9, 'option' => '', 'name' => 'Ibadan South East'],
            ['id' => 10, 'option' => '', 'name' => 'Ibadan South West'],
            ['id' => 11, 'option' => '', 'name' => 'Ibarapa Central'],
            ['id' => 12, 'option' => '', 'name' => 'Ibarapa East'],
            ['id' => 13, 'option' => '', 'name' => 'Ibarapa North'],
            ['id' => 14, 'option' => '', 'name' => 'Ido'],
            ['id' => 15, 'option' => '', 'name' => 'Irepo'],
            ['id' => 16, 'option' => '', 'name' => 'Iseyin'],
            ['id' => 17, 'option' => '', 'name' => 'Itesiwaju'],
            ['id' => 18, 'option' => '', 'name' => 'Iwajowa'],
            ['id' => 19, 'option' => '', 'name' => 'Kajola'],
            ['id' => 20, 'option' => '', 'name' => 'Lagelu Ogbomosho North'],
            ['id' => 21, 'option' => '', 'name' => 'Ogbmosho South'],
            ['id' => 22, 'option' => '', 'name' => 'Ogo Oluwa'],
            ['id' => 23, 'option' => '', 'name' => 'Olorunsogo'],
            ['id' => 24, 'option' => '', 'name' => 'Oluyole'],
            ['id' => 25, 'option' => '', 'name' => 'Ona-Ara'],
            ['id' => 26, 'option' => '', 'name' => 'Orelope'],
            ['id' => 27, 'option' => '', 'name' => 'Ori Ire'],
            ['id' => 28, 'option' => '', 'name' => 'Oyo East'],
            ['id' => 29, 'option' => '', 'name' => 'Oyo West'],
            ['id' => 30, 'option' => '', 'name' => 'Saki East'],
            ['id' => 31, 'option' => '', 'name' => 'Saki West'],
            ['id' => 32, 'option' => '', 'name' => 'Surulere'],
        ],
    ],
    [
        'id' => 31, 'option' => '', 'name' => 'Plateau State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Barikin Ladi'],
            ['id' => 2, 'option' => '', 'name' => 'Bassa'],
            ['id' => 3, 'option' => '', 'name' => 'Bokkos'],
            ['id' => 4, 'option' => '', 'name' => 'Jos East'],
            ['id' => 5, 'option' => '', 'name' => 'Jos North'],
            ['id' => 6, 'option' => '', 'name' => 'Jos South'],
            ['id' => 7, 'option' => '', 'name' => 'Kanam'],
            ['id' => 8, 'option' => '', 'name' => 'Kanke'],
            ['id' => 9, 'option' => '', 'name' => 'Langtang North'],
            ['id' => 10, 'option' => '', 'name' => 'Langtang South'],
            ['id' => 11, 'option' => '', 'name' => 'Mangu'],
            ['id' => 12, 'option' => '', 'name' => 'Mikang'],
            ['id' => 13, 'option' => '', 'name' => 'Pankshin'],
            ['id' => 14, 'option' => '', 'name' => 'Qua\'an Pan'],
            ['id' => 15, 'option' => '', 'name' => 'Riyom'],
            ['id' => 16, 'option' => '', 'name' => 'Shendam'],
            ['id' => 17, 'option' => '', 'name' => 'Wase'],
        ],
    ],
    [
        'id' => 32, 'option' => '', 'name' => 'Rivers State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Abua–Odual'],
            ['id' => 2, 'option' => '', 'name' => 'Ahoada East'],
            ['id' => 3, 'option' => '', 'name' => 'Ahoada West'],
            ['id' => 4, 'option' => '', 'name' => 'Akuku-Toru'],
            ['id' => 5, 'option' => '', 'name' => 'Andoni'],
            ['id' => 6, 'option' => '', 'name' => 'Asari-Toru'],
            ['id' => 7, 'option' => '', 'name' => 'Bonny'],
            ['id' => 8, 'option' => '', 'name' => 'Degema'],
            ['id' => 9, 'option' => '', 'name' => 'Eleme'],
            ['id' => 10, 'option' => '', 'name' => 'Emohua'],
            ['id' => 11, 'option' => '', 'name' => 'Etche'],
            ['id' => 12, 'option' => '', 'name' => 'Gokana'],
            ['id' => 13, 'option' => '', 'name' => 'Ikwerre'],
            ['id' => 14, 'option' => '', 'name' => 'Khana'],
            ['id' => 15, 'option' => '', 'name' => 'Obio-Akpor'],
            ['id' => 16, 'option' => '', 'name' => 'Ogba–Egbema–Ndoni'],
            ['id' => 17, 'option' => '', 'name' => 'Ogu–Bolo'],
            ['id' => 18, 'option' => '', 'name' => 'Okrika'],
            ['id' => 19, 'option' => '', 'name' => 'Omuma'],
            ['id' => 20, 'option' => '', 'name' => 'Opobo–Nkoro'],
            ['id' => 21, 'option' => '', 'name' => 'Oyigbo'],
            ['id' => 22, 'option' => '', 'name' => 'Port-Harcourt'],
            ['id' => 23, 'option' => '', 'name' => 'Tai'],
        ],
    ],
    [
        'id' => 33, 'option' => '', 'name' => 'Sokoto State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Binji'],
            ['id' => 2, 'option' => '', 'name' => 'Bodinga'],
            ['id' => 3, 'option' => '', 'name' => 'Dange-shnsi'],
            ['id' => 4, 'option' => '', 'name' => 'Gada'],
            ['id' => 5, 'option' => '', 'name' => 'Goronyo'],
            ['id' => 6, 'option' => '', 'name' => 'Gudu'],
            ['id' => 7, 'option' => '', 'name' => 'Gawabawa'],
            ['id' => 8, 'option' => '', 'name' => 'Illela'],
            ['id' => 9, 'option' => '', 'name' => 'Isa'],
            ['id' => 10, 'option' => '', 'name' => 'Kware'],
            ['id' => 11, 'option' => '', 'name' => 'kebbe'],
            ['id' => 12, 'option' => '', 'name' => 'Rabah'],
            ['id' => 13, 'option' => '', 'name' => 'Sabon birni'],
            ['id' => 14, 'option' => '', 'name' => 'Shagari'],
            ['id' => 15, 'option' => '', 'name' => 'Silame'],
            ['id' => 16, 'option' => '', 'name' => 'Sokoto North'],
            ['id' => 17, 'option' => '', 'name' => 'Sokoto South'],
            ['id' => 18, 'option' => '', 'name' => 'Tambuwal'],
            ['id' => 19, 'option' => '', 'name' => 'Tqngaza'],
            ['id' => 20, 'option' => '', 'name' => 'Tureta'],
            ['id' => 21, 'option' => '', 'name' => 'Wamako'],
            ['id' => 22, 'option' => '', 'name' => 'Wurno'],
            ['id' => 23, 'option' => '', 'name' => 'Yabo'],
        ],
    ],
    [
        'id' => 34, 'option' => '', 'name' => 'Taraba State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Ardo-kola'],
            ['id' => 2, 'option' => '', 'name' => 'Bali'],
            ['id' => 3, 'option' => '', 'name' => 'Donga'],
            ['id' => 4, 'option' => '', 'name' => 'Gashaka'],
            ['id' => 5, 'option' => '', 'name' => 'Cassol'],
            ['id' => 6, 'option' => '', 'name' => 'Ibi'],
            ['id' => 7, 'option' => '', 'name' => 'Jalingo'],
            ['id' => 8, 'option' => '', 'name' => 'Karin-Lamido'],
            ['id' => 9, 'option' => '', 'name' => 'Kurmi'],
            ['id' => 10, 'option' => '', 'name' => 'Lau'],
            ['id' => 11, 'option' => '', 'name' => 'Sardauna'],
            ['id' => 12, 'option' => '', 'name' => 'Takum'],
            ['id' => 13, 'option' => '', 'name' => 'Ussa'],
            ['id' => 14, 'option' => '', 'name' => 'Wukari'],
            ['id' => 15, 'option' => '', 'name' => 'Yorro'],
            ['id' => 16, 'option' => '', 'name' => 'Zing'],
        ],
    ],
    [
        'id' => 35, 'option' => '', 'name' => 'Yobe State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Bade'],
            ['id' => 2, 'option' => '', 'name' => 'Bursari'],
            ['id' => 3, 'option' => '', 'name' => 'Damaturu'],
            ['id' => 4, 'option' => '', 'name' => 'Fika'],
            ['id' => 5, 'option' => '', 'name' => 'Fune'],
            ['id' => 6, 'option' => '', 'name' => 'Geidam'],
            ['id' => 7, 'option' => '', 'name' => 'Gujba'],
            ['id' => 8, 'option' => '', 'name' => 'Gulani'],
            ['id' => 9, 'option' => '', 'name' => 'Jakusko'],
            ['id' => 10, 'option' => '', 'name' => 'Karasuwa'],
            ['id' => 11, 'option' => '', 'name' => 'Karawa'],
            ['id' => 12, 'option' => '', 'name' => 'Machina'],
            ['id' => 13, 'option' => '', 'name' => 'Nangere'],
            ['id' => 14, 'option' => '', 'name' => 'Nguru Potiskum'],
            ['id' => 15, 'option' => '', 'name' => 'Tarmua'],
            ['id' => 16, 'option' => '', 'name' => 'Yunusari'],
            ['id' => 17, 'option' => '', 'name' => 'Yusufari'],
        ],
    ],
    [
        'id' => 36, 'option' => '', 'name' => 'Zamfara State', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Anka'],
            ['id' => 2, 'option' => '', 'name' => 'Bakura'],
            ['id' => 3, 'option' => '', 'name' => 'Birnin Magaji'],
            ['id' => 4, 'option' => '', 'name' => 'Bukkuyum'],
            ['id' => 5, 'option' => '', 'name' => 'Bungudu'],
            ['id' => 6, 'option' => '', 'name' => 'Gummi'],
            ['id' => 7, 'option' => '', 'name' => 'Gusau'],
            ['id' => 8, 'option' => '', 'name' => 'Kaura'],
            ['id' => 9, 'option' => '', 'name' => 'Namoda'],
            ['id' => 10, 'option' => '', 'name' => 'Maradun'],
            ['id' => 11, 'option' => '', 'name' => 'Maru'],
            ['id' => 12, 'option' => '', 'name' => 'Shinkafi'],
            ['id' => 13, 'option' => '', 'name' => 'Talata Mafara'],
            ['id' => 14, 'option' => '', 'name' => 'Tsafe'],
            ['id' => 15, 'option' => '', 'name' => 'Zurmi'],
        ],
    ],
    [
        'id' => 37, 'option' => '', 'name' => 'Abuja FCT', 'lgas' => [
            ['id' => '', 'option' => 'disabled selected', 'name' => 'Select your LGA...'],
            ['id' => 1, 'option' => '', 'name' => 'Gwagwalada'],
            ['id' => 2, 'option' => '', 'name' => 'Kuje'],
            ['id' => 3, 'option' => '', 'name' => 'Abaji'],
            ['id' => 4, 'option' => '', 'name' => 'Abuja Municipal'],
            ['id' => 5, 'option' => '', 'name' => 'Bwari'],
            ['id' => 6, 'option' => '', 'name' => 'Kwali'],
        ],
    ],
];

foreach ($states as $state) {
    if ($state['id'] == $state_id) {
        # code...
        $lgas = $state['lgas'];
        foreach ($lgas as $lga) {
            ?>
            <option id="<?php echo $lga['id']; ?>" <?php echo $lga['option']; ?> >
                <?php echo $lga['name']; ?>
            </option>
            <?php
        }
    }
}